#!/usr/bin/env bash
# Install nginx on your web-01
# it must return a page that contains the string Hello World!

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
$toAdd = `
location /redirect_me/ {
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
`
sudo echo $toAdd >> /etc/nginx/sites-available/default
sudo service nginx start
