#!/usr/bin/env bash
# configure haproxy load palancer
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "\
frontend Xs55kh
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 54.90.30.64:80
    server web-02 52.90.15.99:80
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
