#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

str_to_be_displayed="Best School"
range=$(seq 1 10) # == {1..10}
#	seq command to generate a sequence of numbers from 1 to 10

for _ in $range
do
    echo "$str_to_be_displayed"
done
