#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

str_to_be_displayed="Best School"
i="0"
max="10"

until [ $i -eq $max ]
do
    echo "$str_to_be_displayed"
#    i=$[$i+1]
        i=$((i+1))
done
