#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

str_to_be_displayed="Best School"
i="0"
max="10"
fourth="4"
eighth="8"

while [ $i -lt $max ]
do
#    i=$[$i+1]
    i=$((i+1))
    if [ $i -eq $fourth ]
    then
    	echo "bad luck"
    elif [ $i -eq $eighth ]
    then
    	echo "good luck"
    else
        echo "$str_to_be_displayed"
    fi
done
