#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i="1"
max="21"
fourth="4"
ninth="9"
sevth="17"

while [ $i -lt $max ]
do
    if [ $i -eq $fourth ]
    then
        echo "$i"
    	echo "bad luck from China"
    elif [ $i -eq $ninth ]
    then
        echo "$i"
    	echo "bad luck from Japan"
    elif [ $i -eq $sevth ]
    then
        echo "$i"
	echo "bad luck from Italy"
    else
        echo "$i"
    fi
#    i=$[$i+1]
    i=$((i+1))
done
