#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i="1"
max="21"
#fourth="4"
#ninth="9"
#sevth="17"

while [ $i -lt $max ]
do
    case $i in
	4) echo $i
	    echo "bad luck from China"
	    ;;
	9) echo $i
	    echo "bad luck from Japan"
	    ;;
	17) echo $i
	    echo "bad luck from Italy"
	    ;;
	*) echo $i
	    ;;
    esac
    i=$((i+1))
done
