#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

min_ls="60"
hour_st="0"
hour_ls="12"

while [ $hour_st -le $hour_ls ]
do
    echo "Hour: $hour_st"
    min_st="1"
    while [ $min_st -lt $min_ls ]
    do
        echo "$min_st"
#	min_st=$((min_st+1))
	(( ++min_st ))
    done
#    hour_st=$((hour_st+1))
    (( ++hour_st ))
done
