#!/usr/bin/env bash
# displays: The content of the current directory In a list format

listing="$(ls)"
#index="[index("-")+1:]"

for i in $listing
do
#    echo "$i$index"
#    echo "${i#*-}"
    echo "$i" | cut -d '-' -f2
done
